version: '3'

services:
  app:
    container_name: APP
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    volumes:
      - ./src/main/resources/static:/src/main/resources/static

  mysql:
    container_name: MYSQL
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: musicsite
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d/:ro
      - dbdata:/var/lib/mysql

  adminer:
    container_name: ADMINER
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    depends_on:
      - mysql

volumes:
  dbdata: